#ifndef _GLOBALS_H 
#define _GLOBALS_H

/*! 
\file globals.h
#include "lrun.h"
#include "web_api.h"
#include "lrw_custom_body.h"


\brief Generated by VuGen to define c headers: files included from where LoadRunner was installed. 
*/


#ifndef _GLOBALS_H 
#define _GLOBALS_H

//--------------------------------------------------------------------
// Include Files











//--------------------------------------------------------------------
// Global Variables














#endif // _GLOBALS_H
