//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : More etails are at http://wilsonmar.github.io/javascript-in-loadrunner
//"                                     and http://wilsonmar.github.io/loadrunner-javascript-coding
//"                      
//" Script Author      : Wilson Mar
//" Script Date        : Tue Apr 05 13:15:10 2016
//" Generated By       : LoadRunner Recorder (Build: 1096)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


function vuser_init()
{
	var rc=0;
	
    rc=wi_library_init();
    
	return rc;
}

