//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : More etails are at http://wilsonmar.github.io/javascript-in-loadrunner
//"                                     and http://wilsonmar.github.io/loadrunner-javascript-coding
//"                      
//" Script Author      : Wilson Mar
//" Script Date        : Tue Apr 05 13:15:10 2016
//" Generated By       : LoadRunner Recorder (Build: 1096)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

var RunDataIn  = lr.getAttribString("RunDataIn"); // controls Input data source (file, VTS).
var RunDataIn_key;
var RunDataIn_rows;
var RunType    = lr.getAttribString("RunType");   // controls scope of script generic processing (URL_Landing, SignUp, SignIn, SignOut).
var Retries    = lr.getAttribString("Retries");   // maximum number of retries before giving up.

function vuser_init()
{
    var rc=0;
	
    rc=wi_library_init();
    
    if( RunDataIn === undefined){
    	RunDataIn = "1"; // the default, not "FILE" or "VTS".
    	lr.outputMessage(">> RunDataIn not defined. Using default "+ RunDataIn +".");
    }else{
    	RunDataIn = RunDataIn.toUpperCase();
    }

   	if( RunDataIn === "1"){
     	rc=WJS1_Access_landing( "T01_landing","http://127.0.0.1:1080/WebTours/index.htm",100);
		if( rc != 0 ){ return rc; }

    }else
	if( RunDataIn === "FILE"){ // Loop thru file run_01.dat
    	RunDataIn_rows = wi_file_count( "{run_URL}" ); // Find count in file for looping.
    	lr.outputMessage(">> RunDataIn =\""+ RunDataIn +"\", wi_file_count finds "+ RunDataIn_rows +" rows.");

    }else
	if( RunDataIn === "VTS"){
		// OK

    }else{
		lr.errorMessage(">> Run-Time Settings Attribute RunDataIn="+ RunDataIn +" not recognized."); 
		lr.abort();
    }

	return rc;
}

