//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : 
//"                      
//"                      
//" Script Author      : Wilson Mar
//" Script Date        : Tue Apr 05 13:15:10 2016
//" Generated By       : LoadRunner Recorder (Build: 1096)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


function vuser_init()
{
		
    wi_library_init();
	wi_msg_level_print( wi_msg_level_at_entry );

	return 0;
}

