/*! 
\file Action.c
\brief Generated by VuGen to call functions which are automatically invoked every iteration during run. 
*/

// Au
Action()
{
	int rc=LR_PASS;
	int i=0;
	
	/// Call functions only during the first iteration, as if they were inside vuser_init().
	     iActionIterations++; // increment from zero value defined in vuser_init.
	 if( iActionIterations == 1){
		srand(time(NULL)); // Seed random number rand().

		UserIds_file_recs=vi_set_UserIds_file_recs(); 
			lr_error_message(">> rc=%d",rc);
			if( UserIds_file_recs <= 0 ){ rc = UserIds_file_recs; return rc; }
		WT3_SignUpInOut_Init(); // establish variables.
  
		LPCSTR_HostPath = lr_get_attrib_string("HostPath");	// LPSTR is Attribute defined in Vuser_init. 
		lr_save_string(LPCSTR_HostPath,"WebToursPath");
		wi_startPrintingInfo();
		lr_output_message(">> {WebToursPath}=%s", lr_eval_string("{WebToursPath}"));
		wi_resetPrinting();

		wi_save_request_header(); // to wi_show_user_agent() later.		
		lr_save_string("WT3_T03_URL_Landing_1","pTransName");
 		rc=WT3_URL_Landing(); // just for establishing state to invoke run conditions.
 		wi_show_user_agent();
 		WT3_Config_Run_Conditions();
 		WT3_Print_Run_Conditions();
 		WT3_Invoke_Run_Conditions();

 		WT3_SignUp_Data();
	 }

	rc=WT3_SignUpInOut(); // to handle specified RunType attribute.

	if( rc == LR_PASS ){
		rc=WT3_Travel(); // to handle specified UseCase attribute.
	}

	rc=WT3_SignOut_handle();
	
	return rc;
}
